name: food_delivery
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  relative_scale:
  provider:
  localregex:
  flutter_platform_widgets:
  package_info_plus:
  uuid:
  shared_preferences:
  get_it:
  dio:
  intl:
  path_provider:
  money_formatter:
  connectivity_plus:
  json_annotation:
  flutter_map: ^1.1.0
  location: ^4.4.0

dev_dependencies:
  build_runner:
  json_serializable:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Rubik
      fonts:
        - asset: fonts/Rubik-Light.ttf
          weight: 300
        - asset: fonts/Rubik-Regular.ttf
          weight: 400
        - asset: fonts/Rubik-Medium.ttf
          weight: 500
        - asset: fonts/Rubik-SemiBold.ttf
          weight: 600
        - asset: fonts/Rubik-Bold.ttf
          weight: 700
        - asset: fonts/Rubik-ExtraBold.ttf
          weight: 800
        - asset: fonts/Rubik-Black.ttf
          weight: 900
